const datatable = [
  {
    Titel: "Metastatisk brystkræft - i både øvre og nedre torso",
    Diagnosegruppe: "Fælles",
    Status_ID: 5,
    StartDato: "2019-01-01",
    SlutDato: "2022-08-01",
    Diagnose: "Brystkræft",
    KFE_Nr: "1911",
    Kaldenavn: "Primus",
    Behandlingstype: "Protokol",
    Protokolstatus: "i gang, inklusion åben",
    Fase: "Fase II",
    Initiering: "Firma",
    InvNavn: "Anders Boye",
    PsplNavn: "Anne Jensen",
    ForvAntalPatienter_PrAar: 3,
    ForvAntalPatienter_Ialt: 9,
    Antal36: 2,
    Antal60: 5,
    AntalPatienter: 20,
  },
  {
    Titel: "Metastatisk brystkræft - i både øvre og nedre torso",
    Diagnosegruppe: "A",
    Status_ID: 4,
    StartDato: "2019-01-01",
    SlutDato: "2022-08-01",
    Diagnose: "Brystkræft",
    KFE_Nr: "1911",
    Kaldenavn: "Primus",
    Behandlingstype: "Protokol",
    Protokolstatus: "i gang, inklusion åben",
    Fase: "Fase II",
    Initiering: "Firma",
    InvNavn: "Anders Boye",
    PsplNavn: "Anne Jensen",
    ForvAntalPatienter_PrAar: 3,
    ForvAntalPatienter_Ialt: 9,
    Antal36: 2,
    Antal60: 5,
    AntalPatienter: 20,
  },
  {
    Titel: "Colorectal Cancer - Immunotherapy",
    Diagnosegruppe: "D",
    Status_ID: 4,
    StartDato: "2020-08-20",
    SlutDato: "2023-04-15",
    Diagnose: "Colorectal Cancer",
    KFE_Nr: "2278",
    Kaldenavn: "Momentum",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Government Agency",
    InvNavn: "Jessica White",
    PsplNavn: "Andrew Carter",
    ForvAntalPatienter_PrAar: 6,
    ForvAntalPatienter_Ialt: 90,
    Antal36: 25,
    Antal60: 50,
    AntalPatienter: 80,
  },
  {
    Titel: "Pancreatic Cancer - Targeted Therapy",
    Diagnosegruppe: "A",
    Status_ID: 5,
    StartDato: "2019-05-12",
    SlutDato: "2022-11-30",
    Diagnose: "Pancreatic Cancer",
    KFE_Nr: "1934",
    Kaldenavn: "Vanguard",
    Behandlingstype: "Experimental Treatment",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Biotech Company",
    InvNavn: "Richard Martinez",
    PsplNavn: "Linda Garcia",
    ForvAntalPatienter_PrAar: 4,
    ForvAntalPatienter_Ialt: 75,
    Antal36: 30,
    Antal60: 60,
    AntalPatienter: 70,
  },
  {
    Titel: "Lung Cancer - Advanced Stage",
    Diagnosegruppe: "B",
    Status_ID: 3,
    StartDato: "2020-03-15",
    SlutDato: "2023-11-30",
    Diagnose: "Lung Cancer",
    KFE_Nr: "2032",
    Kaldenavn: "Phoenix",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Academic Institution",
    InvNavn: "Emily Thompson",
    PsplNavn: "David Miller",
    ForvAntalPatienter_PrAar: 5,
    ForvAntalPatienter_Ialt: 120,
    Antal36: 40,
    Antal60: 80,
    AntalPatienter: 110,
  },
  {
    Titel: "Prostate Cancer - Hormone Therapy",
    Diagnosegruppe: "C",
    Status_ID: 1,
    StartDato: "2021-06-10",
    SlutDato: "2024-12-01",
    Diagnose: "Prostate Cancer",
    KFE_Nr: "2156",
    Kaldenavn: "Spartan",
    Behandlingstype: "Observational Study",
    Protokolstatus: "pending approval",
    Fase: "N/A",
    Initiering: "Pharmaceutical Company",
    InvNavn: "Karen Johnson",
    PsplNavn: "Michael Davis",
    ForvAntalPatienter_PrAar: 8,
    ForvAntalPatienter_Ialt: 200,
    Antal36: 30,
    Antal60: 60,
    AntalPatienter: 150,
  },
  {
    Titel: "Ovarian Cancer - Combination Therapy",
    Diagnosegruppe: "C",
    Status_ID: 4,
    StartDato: "2021-02-10",
    SlutDato: "2024-09-30",
    Diagnose: "Ovarian Cancer",
    KFE_Nr: "2056",
    Kaldenavn: "Harmony",
    Behandlingstype: "Phase II Trial",
    Protokolstatus: "in progress, enrollment open",
    Fase: "Phase II",
    Initiering: "Academic Institution",
    InvNavn: "Sarah Turner",
    PsplNavn: "John Anderson",
    ForvAntalPatienter_PrAar: 7,
    ForvAntalPatienter_Ialt: 150,
    Antal36: 35,
    Antal60: 70,
    AntalPatienter: 120,
  },
  {
    Titel: "Melanoma - Immunotherapy",
    Diagnosegruppe: "B",
    Status_ID: 5,
    StartDato: "2018-11-15",
    SlutDato: "2022-07-01",
    Diagnose: "Melanoma",
    KFE_Nr: "1889",
    Kaldenavn: "Radiance",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Pharmaceutical Company",
    InvNavn: "Christopher Brown",
    PsplNavn: "Rachel Miller",
    ForvAntalPatienter_PrAar: 5,
    ForvAntalPatienter_Ialt: 100,
    Antal36: 25,
    Antal60: 50,
    AntalPatienter: 90,
  },
  {
    Titel: "Leukemia - Targeted Therapy",
    Diagnosegruppe: "D",
    Status_ID: 4,
    StartDato: "2020-06-25",
    SlutDato: "2023-12-15",
    Diagnose: "Leukemia",
    KFE_Nr: "2222",
    Kaldenavn: "Eclipse",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Biotech Company",
    InvNavn: "Alexandra Mitchell",
    PsplNavn: "Robert Turner",
    ForvAntalPatienter_PrAar: 6,
    ForvAntalPatienter_Ialt: 80,
    Antal36: 20,
    Antal60: 40,
    AntalPatienter: 70,
  },
  {
    Titel: "Gastric Cancer - Immunotherapy",
    Diagnosegruppe: "A",
    Status_ID: 5,
    StartDato: "2019-09-10",
    SlutDato: "2022-12-31",
    Diagnose: "Gastric Cancer",
    KFE_Nr: "1978",
    Kaldenavn: "Spectrum",
    Behandlingstype: "Experimental Treatment",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Academic Institution",
    InvNavn: "Michelle Taylor",
    PsplNavn: "Daniel Lewis",
    ForvAntalPatienter_PrAar: 4,
    ForvAntalPatienter_Ialt: 60,
    Antal36: 15,
    Antal60: 30,
    AntalPatienter: 50,
  },
  {
    Titel: "Head and Neck Cancer - Radiotherapy",
    Diagnosegruppe: "B",
    Status_ID: 4,
    StartDato: "2020-04-05",
    SlutDato: "2023-10-20",
    Diagnose: "Head and Neck Cancer",
    KFE_Nr: "2145",
    Kaldenavn: "RadiantBeam",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Government Agency",
    InvNavn: "Jonathan Anderson",
    PsplNavn: "Sophie Moore",
    ForvAntalPatienter_PrAar: 5,
    ForvAntalPatienter_Ialt: 70,
    Antal36: 20,
    Antal60: 45,
    AntalPatienter: 60,
  },
  {
    Titel: "Hepatocellular Carcinoma - Immunotherapy",
    Diagnosegruppe: "C",
    Status_ID: 5,
    StartDato: "2019-07-15",
    SlutDato: "2023-03-01",
    Diagnose: "Hepatocellular Carcinoma",
    KFE_Nr: "1998",
    Kaldenavn: "ImmunoGuard",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Pharmaceutical Company",
    InvNavn: "Megan Turner",
    PsplNavn: "Christopher Ward",
    ForvAntalPatienter_PrAar: 6,
    ForvAntalPatienter_Ialt: 90,
    Antal36: 30,
    Antal60: 60,
    AntalPatienter: 80,
  },
  {
    Titel: "Renal Cell Carcinoma - Targeted Therapy",
    Diagnosegruppe: "D",
    Status_ID: 4,
    StartDato: "2020-10-10",
    SlutDato: "2024-04-30",
    Diagnose: "Renal Cell Carcinoma",
    KFE_Nr: "2321",
    Kaldenavn: "RenalShield",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Biotech Company",
    InvNavn: "Olivia Harris",
    PsplNavn: "Nathan Turner",
    ForvAntalPatienter_PrAar: 8,
    ForvAntalPatienter_Ialt: 100,
    Antal36: 25,
    Antal60: 50,
    AntalPatienter: 90,
  },
  {
    Titel: "Breast Cancer - Neo-adjuvant Chemotherapy",
    Diagnosegruppe: "A",
    Status_ID: 5,
    StartDato: "2019-08-15",
    SlutDato: "2023-02-28",
    Diagnose: "Breast Cancer",
    KFE_Nr: "2012",
    Kaldenavn: "NeoShield",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Academic Institution",
    InvNavn: "Sophie Davis",
    PsplNavn: "Andrew Turner",
    ForvAntalPatienter_PrAar: 6,
    ForvAntalPatienter_Ialt: 80,
    Antal36: 30,
    Antal60: 60,
    AntalPatienter: 70,
  },
  {
    Titel: "Bladder Cancer - Immunotherapy",
    Diagnosegruppe: "B",
    Status_ID: 4,
    StartDato: "2020-12-01",
    SlutDato: "2024-06-30",
    Diagnose: "Bladder Cancer",
    KFE_Nr: "2365",
    Kaldenavn: "ImmuBlaze",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Government Agency",
    InvNavn: "Ethan Walker",
    PsplNavn: "Emma Turner",
    ForvAntalPatienter_PrAar: 7,
    ForvAntalPatienter_Ialt: 120,
    Antal36: 35,
    Antal60: 70,
    AntalPatienter: 110,
  },
  {
    Titel: "Thyroid Cancer - Tyrosine Kinase Inhibitors",
    Diagnosegruppe: "C",
    Status_ID: 5,
    StartDato: "2019-04-20",
    SlutDato: "2022-10-15",
    Diagnose: "Thyroid Cancer",
    KFE_Nr: "1945",
    Kaldenavn: "TyroShield",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Pharmaceutical Company",
    InvNavn: "Zoe Mitchell",
    PsplNavn: "William Turner",
    ForvAntalPatienter_PrAar: 5,
    ForvAntalPatienter_Ialt: 80,
    Antal36: 20,
    Antal60: 40,
    AntalPatienter: 70,
  },
  {
    Titel: "Esophageal Cancer - Chemoradiotherapy",
    Diagnosegruppe: "D",
    Status_ID: 4,
    StartDato: "2020-07-10",
    SlutDato: "2023-12-31",
    Diagnose: "Esophageal Cancer",
    KFE_Nr: "2233",
    Kaldenavn: "RadiantEsophX",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Biotech Company",
    InvNavn: "Catherine Turner",
    PsplNavn: "James Harris",
    ForvAntalPatienter_PrAar: 6,
    ForvAntalPatienter_Ialt: 90,
    Antal36: 25,
    Antal60: 50,
    AntalPatienter: 80,
  },
  {
    Titel: "Pancreatic Cancer - Chemotherapy",
    Diagnosegruppe: "A",
    Status_ID: 5,
    StartDato: "2019-10-01",
    SlutDato: "2023-04-15",
    Diagnose: "Pancreatic Cancer",
    KFE_Nr: "2001",
    Kaldenavn: "ChemoGuard",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Academic Institution",
    InvNavn: "Benjamin Turner",
    PsplNavn: "Sophia Mitchell",
    ForvAntalPatienter_PrAar: 7,
    ForvAntalPatienter_Ialt: 110,
    Antal36: 30,
    Antal60: 60,
    AntalPatienter: 100,
  },
  {
    Titel: "Cervical Cancer - Targeted Therapy",
    Diagnosegruppe: "B",
    Status_ID: 4,
    StartDato: "2020-11-15",
    SlutDato: "2024-05-31",
    Diagnose: "Cervical Cancer",
    KFE_Nr: "2310",
    Kaldenavn: "CerviShield",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Government Agency",
    InvNavn: "Emma Harris",
    PsplNavn: "Lucas Turner",
    ForvAntalPatienter_PrAar: 8,
    ForvAntalPatienter_Ialt: 130,
    Antal36: 40,
    Antal60: 80,
    AntalPatienter: 120,
  },
  {
    Titel: "Prostate Cancer - Radiopharmaceuticals",
    Diagnosegruppe: "C",
    Status_ID: 5,
    StartDato: "2019-06-01",
    SlutDato: "2023-01-15",
    Diagnose: "Prostate Cancer",
    KFE_Nr: "1965",
    Kaldenavn: "ProstaRadiant",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Pharmaceutical Company",
    InvNavn: "Sophie Turner",
    PsplNavn: "Ryan Harris",
    ForvAntalPatienter_PrAar: 6,
    ForvAntalPatienter_Ialt: 95,
    Antal36: 30,
    Antal60: 60,
    AntalPatienter: 85,
  },
  {
    Titel: "Glioblastoma - Immunotherapy",
    Diagnosegruppe: "D",
    Status_ID: 4,
    StartDato: "2021-01-20",
    SlutDato: "2024-07-31",
    Diagnose: "Glioblastoma",
    KFE_Nr: "2401",
    Kaldenavn: "ImmunoGlio",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Biotech Company",
    InvNavn: "Daniel Harris",
    PsplNavn: "Mia Turner",
    ForvAntalPatienter_PrAar: 7,
    ForvAntalPatienter_Ialt: 110,
    Antal36: 35,
    Antal60: 70,
    AntalPatienter: 100,
  },
  {
    Titel: "Lymphoma - CAR-T Cell Therapy",
    Diagnosegruppe: "A",
    Status_ID: 5,
    StartDato: "2018-12-05",
    SlutDato: "2022-06-15",
    Diagnose: "Lymphoma",
    KFE_Nr: "1867",
    Kaldenavn: "CAR-TShield",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Academic Institution",
    InvNavn: "Isabella Turner",
    PsplNavn: "Noah Harris",
    ForvAntalPatienter_PrAar: 6,
    ForvAntalPatienter_Ialt: 90,
    Antal36: 30,
    Antal60: 60,
    AntalPatienter: 80,
  },
  {
    Titel: "Rectal Cancer - Neoadjuvant Therapy",
    Diagnosegruppe: "B",
    Status_ID: 4,
    StartDato: "2021-04-10",
    SlutDato: "2024-10-31",
    Diagnose: "Rectal Cancer",
    KFE_Nr: "2456",
    Kaldenavn: "NeoRecta",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Government Agency",
    InvNavn: "Elijah Harris",
    PsplNavn: "Ava Turner",
    ForvAntalPatienter_PrAar: 8,
    ForvAntalPatienter_Ialt: 120,
    Antal36: 40,
    Antal60: 80,
    AntalPatienter: 110,
  },
  {
    Titel: "Hodgkin's Lymphoma - Immunotherapy",
    Diagnosegruppe: "C",
    Status_ID: 5,
    StartDato: "2019-11-15",
    SlutDato: "2023-05-30",
    Diagnose: "Hodgkin's Lymphoma",
    KFE_Nr: "2065",
    Kaldenavn: "ImmunoHodgkin",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Pharmaceutical Company",
    InvNavn: "Aiden Turner",
    PsplNavn: "Olivia Harris",
    ForvAntalPatienter_PrAar: 7,
    ForvAntalPatienter_Ialt: 100,
    Antal36: 35,
    Antal60: 70,
    AntalPatienter: 90,
  },
  {
    Titel: "Prostate Cancer - Advanced Hormone Therapy",
    Diagnosegruppe: "D",
    Status_ID: 4,
    StartDato: "2021-08-15",
    SlutDato: "2024-02-29",
    Diagnose: "Prostate Cancer",
    KFE_Nr: "2489",
    Kaldenavn: "HormoGuard",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Biotech Company",
    InvNavn: "Lucas Harris",
    PsplNavn: "Ella Turner",
    ForvAntalPatienter_PrAar: 6,
    ForvAntalPatienter_Ialt: 90,
    Antal36: 25,
    Antal60: 50,
    AntalPatienter: 80,
  },
  {
    Titel: "Pancreatic Cancer - Personalized Medicine",
    Diagnosegruppe: "A",
    Status_ID: 5,
    StartDato: "2020-01-10",
    SlutDato: "2023-07-31",
    Diagnose: "Pancreatic Cancer",
    KFE_Nr: "2102",
    Kaldenavn: "PersonaPan",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Academic Institution",
    InvNavn: "Liam Harris",
    PsplNavn: "Eva Turner",
    ForvAntalPatienter_PrAar: 5,
    ForvAntalPatienter_Ialt: 80,
    Antal36: 30,
    Antal60: 60,
    AntalPatienter: 70,
  },
  {
    Titel: "Lung Cancer - Targeted Therapy",
    Diagnosegruppe: "B",
    Status_ID: 4,
    StartDato: "2021-03-20",
    SlutDato: "2024-09-15",
    Diagnose: "Lung Cancer",
    KFE_Nr: "2540",
    Kaldenavn: "TargetLung",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Government Agency",
    InvNavn: "Ava Turner",
    PsplNavn: "Jack Harris",
    ForvAntalPatienter_PrAar: 7,
    ForvAntalPatienter_Ialt: 120,
    Antal36: 40,
    Antal60: 80,
    AntalPatienter: 110,
  },
  {
    Titel: "Colorectal Cancer - Immunotherapy",
    Diagnosegruppe: "C",
    Status_ID: 5,
    StartDato: "2019-09-01",
    SlutDato: "2023-03-31",
    Diagnose: "Colorectal Cancer",
    KFE_Nr: "2078",
    Kaldenavn: "ImmunoColo",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Pharmaceutical Company",
    InvNavn: "Ethan Turner",
    PsplNavn: "Sophia Harris",
    ForvAntalPatienter_PrAar: 6,
    ForvAntalPatienter_Ialt: 100,
    Antal36: 35,
    Antal60: 70,
    AntalPatienter: 90,
  },
  {
    Titel: "Lung Cancer - Immunotherapy",
    Diagnosegruppe: "B",
    Status_ID: 4,
    StartDato: "2021-06-10",
    SlutDato: "2024-12-31",
    Diagnose: "Lung Cancer",
    KFE_Nr: "2680",
    Kaldenavn: "ImmunoLung",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Government Agency",
    InvNavn: "Jack Turner",
    PsplNavn: "Sophia Harris",
    ForvAntalPatienter_PrAar: 7,
    ForvAntalPatienter_Ialt: 110,
    Antal36: 40,
    Antal60: 80,
    AntalPatienter: 100,
  },
  {
    Titel: "Colorectal Cancer - Chemotherapy",
    Diagnosegruppe: "C",
    Status_ID: 5,
    StartDato: "2019-12-01",
    SlutDato: "2023-06-30",
    Diagnose: "Colorectal Cancer",
    KFE_Nr: "2234",
    Kaldenavn: "ChemoColo",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Pharmaceutical Company",
    InvNavn: "Olivia Turner",
    PsplNavn: "Ethan Harris",
    ForvAntalPatienter_PrAar: 6,
    ForvAntalPatienter_Ialt: 100,
    Antal36: 35,
    Antal60: 70,
    AntalPatienter: 90,
  },
  {
    Titel: "Ovarian Cancer - PARP Inhibitors",
    Diagnosegruppe: "D",
    Status_ID: 4,
    StartDato: "2021-03-15",
    SlutDato: "2024-09-30",
    Diagnose: "Ovarian Cancer",
    KFE_Nr: "2765",
    Kaldenavn: "PARPShield",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Biotech Company",
    InvNavn: "Sophie Harris",
    PsplNavn: "Liam Turner",
    ForvAntalPatienter_PrAar: 8,
    ForvAntalPatienter_Ialt: 120,
    Antal36: 45,
    Antal60: 90,
    AntalPatienter: 110,
  },
  {
    Titel: "Melanoma - Checkpoint Inhibitors",
    Diagnosegruppe: "A",
    Status_ID: 5,
    StartDato: "2020-02-01",
    SlutDato: "2023-08-15",
    Diagnose: "Melanoma",
    KFE_Nr: "2315",
    Kaldenavn: "CheckpointMela",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Academic Institution",
    InvNavn: "Ella Harris",
    PsplNavn: "Noah Turner",
    ForvAntalPatienter_PrAar: 6,
    ForvAntalPatienter_Ialt: 95,
    Antal36: 30,
    Antal60: 60,
    AntalPatienter: 85,
  },
  {
    Titel: "Gastric Cancer - Targeted Therapy",
    Diagnosegruppe: "B",
    Status_ID: 4,
    StartDato: "2021-08-01",
    SlutDato: "2025-01-31",
    Diagnose: "Gastric Cancer",
    KFE_Nr: "2850",
    Kaldenavn: "TargetGastric",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Government Agency",
    InvNavn: "Aiden Turner",
    PsplNavn: "Emma Harris",
    ForvAntalPatienter_PrAar: 7,
    ForvAntalPatienter_Ialt: 130,
    Antal36: 40,
    Antal60: 80,
    AntalPatienter: 120,
  },
  {
    Titel: "Leukemia - CAR-T Cell Therapy",
    Diagnosegruppe: "C",
    Status_ID: 5,
    StartDato: "2020-05-15",
    SlutDato: "2023-11-30",
    Diagnose: "Leukemia",
    KFE_Nr: "2402",
    Kaldenavn: "CAR-TLeuk",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Pharmaceutical Company",
    InvNavn: "Liam Turner",
    PsplNavn: "Ava Harris",
    ForvAntalPatienter_PrAar: 6,
    ForvAntalPatienter_Ialt: 100,
    Antal36: 35,
    Antal60: 70,
    AntalPatienter: 90,
  },
  {
    Titel: "Pancreatic Cancer - Immunotherapy",
    Diagnosegruppe: "D",
    Status_ID: 4,
    StartDato: "2021-09-01",
    SlutDato: "2025-02-28",
    Diagnose: "Pancreatic Cancer",
    KFE_Nr: "2901",
    Kaldenavn: "ImmunoPancrea",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Biotech Company",
    InvNavn: "Emma Turner",
    PsplNavn: "Aiden Harris",
    ForvAntalPatienter_PrAar: 8,
    ForvAntalPatienter_Ialt: 140,
    Antal36: 50,
    Antal60: 100,
    AntalPatienter: 130,
  },
  {
    Titel: "Prostate Cancer - Androgen Receptor Inhibitors",
    Diagnosegruppe: "A",
    Status_ID: 5,
    StartDato: "2020-06-15",
    SlutDato: "2024-01-31",
    Diagnose: "Prostate Cancer",
    KFE_Nr: "2480",
    Kaldenavn: "AndroGuard",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Academic Institution",
    InvNavn: "Noah Turner",
    PsplNavn: "Sophia Harris",
    ForvAntalPatienter_PrAar: 7,
    ForvAntalPatienter_Ialt: 110,
    Antal36: 45,
    Antal60: 90,
    AntalPatienter: 100,
  },
  {
    Titel: "Breast Cancer - CDK4/6 Inhibitors",
    Diagnosegruppe: "B",
    Status_ID: 4,
    StartDato: "2021-04-15",
    SlutDato: "2024-10-31",
    Diagnose: "Breast Cancer",
    KFE_Nr: "2985",
    Kaldenavn: "CDKShield",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Government Agency",
    InvNavn: "Sophia Turner",
    PsplNavn: "Liam Harris",
    ForvAntalPatienter_PrAar: 7,
    ForvAntalPatienter_Ialt: 120,
    Antal36: 40,
    Antal60: 80,
    AntalPatienter: 110,
  },
  {
    Titel: "Lung Cancer - Targeted Radiation",
    Diagnosegruppe: "C",
    Status_ID: 5,
    StartDato: "2020-01-01",
    SlutDato: "2023-07-15",
    Diagnose: "Lung Cancer",
    KFE_Nr: "2567",
    Kaldenavn: "RadiantLung",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Pharmaceutical Company",
    InvNavn: "Ella Turner",
    PsplNavn: "Jack Harris",
    ForvAntalPatienter_PrAar: 6,
    ForvAntalPatienter_Ialt: 95,
    Antal36: 30,
    Antal60: 60,
    AntalPatienter: 85,
  },
  {
    Titel: "Prostate Cancer - Hormone Therapy",
    Diagnosegruppe: "D",
    Status_ID: 4,
    StartDato: "2021-10-01",
    SlutDato: "2025-03-31",
    Diagnose: "Prostate Cancer",
    KFE_Nr: "3052",
    Kaldenavn: "HormoProsta",
    Behandlingstype: "Randomized Control Trial",
    Protokolstatus: "in progress, enrollment closed",
    Fase: "Phase II",
    Initiering: "Biotech Company",
    InvNavn: "Liam Harris",
    PsplNavn: "Emma Turner",
    ForvAntalPatienter_PrAar: 8,
    ForvAntalPatienter_Ialt: 140,
    Antal36: 50,
    Antal60: 100,
    AntalPatienter: 130,
  },
  {
    Titel: "Colorectal Cancer - Targeted Immunotherapy",
    Diagnosegruppe: "A",
    Status_ID: 5,
    StartDato: "2020-07-15",
    SlutDato: "2024-02-29",
    Diagnose: "Colorectal Cancer",
    KFE_Nr: "2619",
    Kaldenavn: "ImmunoColo",
    Behandlingstype: "Clinical Trial",
    Protokolstatus: "completed",
    Fase: "Phase III",
    Initiering: "Academic Institution",
    InvNavn: "Noah Turner",
    PsplNavn: "Sophia Harris",
    ForvAntalPatienter_PrAar: 7,
    ForvAntalPatienter_Ialt: 110,
    Antal36: 45,
    Antal60: 90,
    AntalPatienter: 100,
  },
];

export default datatable;
